### ISSUE TITLE
kontena register isn't work

### ISSUE THREAD

**Issue by philipz** [kontena/docs#1]
Run "kontena register" was always get error.
Then vagrant ssh kontena_server, and set EMAIL env, `export EMAIL=youremail@domain.com` , to fix this problem.
Please modify the [Vagrant](https://gist.github.com/nevalla/3c5d962c99b23f1f2fb2), thanks!

**Comment by nevalla** [comment]
Kontena has a global account system, so you need to register only once. If you already have a Kontena account you can just start Kontena with `$ EMAIL='your_kontena_account_email' vagrant up` and login with that account to Kontena server. I think we should update our documentation regarding this.

If this does not solve your problem, could you please tell what kind of error message do you get?

**Comment by tee33** [comment]
Run the following: kontena  service deploy ghost-blog
error: {"nodes":"Too few applicable nodes available"}.
