### ISSUE TITLE
kontena service deploy ghost-blog error: {"nodes":"Too few applicable nodes available"}.

### ISSUE THREAD

**Issue by tee33** [kontena/docs#2]
When running "kontena service deploy ghot-blog", received an error messages: error: {"nodes":"Too few applicable nodes available"}.

**Comment by nevalla** [comment]
Do you have any Kontena agents running? 

Another reason might be that you have already exposed the same port to some other service than you have defined to your ghost-blog service.

**Comment by tee33** [comment]
These were created using the Vagrantfile, even shutting down the node_1 / node_2, still an issue.
vagrant status
Current machine states:
kontena_server            running (virtualbox)
node_1                    running (virtualbox)
node_2                    running (virtualbox)

kontena service list
NAME                           IMAGE                                    INSTANCES  STATEFUL
ghost-blog                     ghost:0.5                                1          yes     

kontena service deploy ghost-blog 
error: {"nodes":"Too few applicable nodes available"}.

**Comment by nevalla** [comment]
If you list connected nodes `kontena node list`, can you see those nodes correctly?

**Comment by nevalla** [comment]
I have tested Vagrantfile setup and identified some errors related to 0.6 release. I will open issue about this on https://github.com/kontena/kontena repository.

**Comment by nevalla** [comment]
Vagrantfile is now fixed on kontena/kontena repository: https://github.com/kontena/kontena/blob/master/docs/getting-started/Vagrantfile

Thanks for adducing this issue. We have merged our repositories to kontena/kontena repository so please open future issues there.
